n= 'curso em video python'
print(len(n))
print(n[0:14])
print(n[14:21])
print(n.find('deo'))
print(n.count('o'))
print('video'in(n))
print(n.replace('curso','adroid'))
print(n.upper())
print(n.lower())
print(n)